import type { Metadata } from "next";
import { Inter } from "next/font/google";
import EarningsOverview from "./EarningsOverview";
// import { usePathname } from "next/navigation";
import "./globals.css";
import Nav from "./Nav";
import SideBar from "./SideBar";
import { headers } from "next/headers";
import Head from "next/head";
// import { Viewport } from "next";

import type { Viewport } from "next";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:
    "Reward Summary | view all your cashback history and manage your account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </Head>
      <body className={inter.className}>
        <Nav />
        <div className="grid main">
          <SideBar />
          <main>
            <EarningsOverview />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
